### ISSUE TITLE
rm it

### ISSUE THREAD

**Issue by Yumcoder-dev** [roxana-ahmadi/datafilter#1]
https://github.com/roxana-ahmadi/datafilter/blob/b344e05a091798af59f825d45673c71a09ba4d71/src/component/oprand/oprandController.js#L29

**Comment by roxana-ahmadi** [comment]
fixed in [#b344e05](https://github.com/roxana-ahmadi/datafilter/commit/b344e05a091798af59f825d45673c71a09ba4d71)
