### ISSUE TITLE
rename and change input parameter

### ISSUE THREAD

**Issue by Yumcoder-dev** [roxana-ahmadi/datafilter#4]
https://github.com/roxana-ahmadi/datafilter/blob/b344e05a091798af59f825d45673c71a09ba4d71/src/component/clouse/ClouseView.jsx#L71

**Comment by roxana-ahmadi** [comment]
fixed in [#ca03745](https://github.com/roxana-ahmadi/datafilter/commit/ca037455d1e6c5148d5360e4201e56976b0ce26c)
