### ISSUE TITLE
get from props

### ISSUE THREAD

**Issue by Yumcoder-dev** [roxana-ahmadi/datafilter#6]
https://github.com/roxana-ahmadi/datafilter/blob/b344e05a091798af59f825d45673c71a09ba4d71/src/component/clouse/ClouseView.jsx#L11

**Comment by roxana-ahmadi** [comment]
fixed in [#fad2117](https://github.com/roxana-ahmadi/datafilter/commit/fad21170917abda2d93f0bf4bf941d76c096544c)
