### ISSUE TITLE
rm

### ISSUE THREAD

**Issue by Yumcoder-dev** [roxana-ahmadi/datafilter#9]
https://github.com/roxana-ahmadi/datafilter/blob/ca037455d1e6c5148d5360e4201e56976b0ce26c/src/component/clouse/clouseController.js#L78

**Comment by roxana-ahmadi** [comment]
fiexd[#fad2117](https://github.com/roxana-ahmadi/datafilter/commit/fad21170917abda2d93f0bf4bf941d76c096544c)
